---
title: "Arbeidskrav 5"
author: "Kristoffer Solum"
date: "16 11 2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
remotes::install_github("dhammarstrom/exscidata")

library(tidyverse)
library(exscidata)
data("dxadata") 
data("strengthvolume")
```




```{r}
library(tidyverse)
dat <- dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sets, sex, leg, lean.mass) %>%
  
  pivot_wider(names_from = time,
              values_from = lean.mass) %>%
  mutate(lbm.change = post - pre) %>%
  mutate(pre.mc = pre - mean(pre)) %>% 
  mutate(prosentvis.endring = ((post - pre) / pre) * 100) %>%
  filter(!is.na(lbm.change)) %>%

  
  print()
  
  
  


dat %>%
  group_by(sets) %>%
  summarise(m = mean(prosentvis.endring),
            sd = sd(prosentvis.endring)) %>%

print()






library(lme4)
library(lmerTest)
m0 <- lm(post ~ pre + sex + sets, data = dat)
m1 <- lmerTest::lmer(post ~ pre + sets + (1|participant), data = dat)
m2 <- lme4::lmer(post ~ pre + sex + sets + (1|participant), data = dat)
plot(m2)
summary(m0)
summary(m1)
summary(m2)
confint(m2)
```







```{r}

modeldat <- dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
   mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sets, sex, leg, lean.mass) %>%
  group_by(participant) %>%
  mutate(n = n(), group = factor(sets, levels = c("single", "multiple")), time = factor(time, levels = c("pre", "post"))) %>%
  
  print()




modeldat %>%
 ggplot(aes(time, lean.mass, group = paste(participant, group), color = group)) + geom_line() + theme_minimal()
```




```{r}

styrke1 <- strengthvolume %>%
  filter(!is.na(load)) %>%
  group_by(exercise) %>%
  mutate(scaled.load = load / max(load, na.rm = TRUE)) %>%
  group_by(participant, time, sex, sets) %>%
  summarise(combined.load = mean(scaled.load, na.rm = TRUE)) %>%
  ungroup() %>%
  
  
  pivot_wider(names_from = time,
              values_from = combined.load) %>%
  mutate(prosentvis.endring = ((post - pre) / pre) * 100) %>%
  
  print()


styrke1 %>%    
  filter(!is.na(post)) %>%
  group_by(sets) %>%
  summarise(m = mean(prosentvis.endring),
            sd = sd(prosentvis.endring)) %>%

print()



styrkemodell <- strengthvolume %>%
  group_by(exercise) %>%
  mutate(scaled.load = load / max(load, na.rm = TRUE)) %>%
  group_by(participant, time, sex, sets) %>%
  summarise(combined.load = mean(scaled.load, na.rm = TRUE)) %>%
  ungroup() %>%
  
  print()

styrkemodell %>%
  filter(!is.na(combined.load), time == factor(time, levels = c("pre", "post"))) %>%
  mutate(time = factor(time, levels = c("pre", "post")),
         group = factor(sets, levels = c("single", "multiple"))) %>%
 ggplot(aes(time, combined.load, group = paste(participant, sets), color = sets)) + geom_line() + theme_minimal() %>%

print()



```










